land = [
    "Artificial surfaces;Urban fabric;Continuous urban fabric",
    "Artificial surfaces;Urban fabric;Discontinuous urban fabric",
    "Artificial surfaces;Industrial, commercial and transport units;Industrial or commercial units",
    "Artificial surfaces;Industrial, commercial and transport units;Road and rail networks and associated land",
    "Artificial surfaces;Industrial, commercial and transport units;Port areas",
    "Artificial surfaces;Industrial, commercial and transport units;Airports",
    "Artificial surfaces;Mine, dump and construction sites;Mineral extraction sites",
    "Artificial surfaces;Mine, dump and construction sites;Dump sites",
    "Artificial surfaces;Mine, dump and construction sites;Construction sites",
    "Artificial surfaces;Artificial, non-agricultural vegetated areas;Green urban areas",
    "Artificial surfaces;Artificial, non-agricultural vegetated areas;Sport and leisure facilities",
    "Agricultural areas;Arable land;Non-irrigated arable land",
    "Agricultural areas;Arable land;Permanently irrigated land",
    "Agricultural areas;Arable land;Rice fields",
    "Agricultural areas;Permanent crops;Vineyards",
    "Agricultural areas;Permanent crops;Fruit trees and berry plantations",
    "Agricultural areas;Permanent crops;Olive groves",
    "Agricultural areas;Pastures;Pastures",
    "Agricultural areas;Heterogeneous agricultural areas;Annual crops associated with permanent crops",
    "Agricultural areas;Heterogeneous agricultural areas;Complex cultivation patterns",
    "Agricultural areas;Heterogeneous agricultural areas;Land principally occupied by agriculture, with significant areas of natural vegetation",
    "Agricultural areas;Heterogeneous agricultural areas;Agro-forestry areas",
    "Forest and semi natural areas;Forests;Broad-leaved forest",
    "Forest and semi natural areas;Forests;Coniferous forest",
    "Forest and semi natural areas;Forests;Mixed forest",
    "Forest and semi natural areas;Scrub and/or herbaceous vegetation associations;Natural grasslands",
    "Forest and semi natural areas;Scrub and/or herbaceous vegetation associations;Moors and heathland",
    "Forest and semi natural areas;Scrub and/or herbaceous vegetation associations;Sclerophyllous vegetation",
    "Forest and semi natural areas;Scrub and/or herbaceous vegetation associations;Transitional woodland-shrub",
    "Forest and semi natural areas;Open spaces with little or no vegetation;Beaches, dunes, sands",
    "Forest and semi natural areas;Open spaces with little or no vegetation;Bare rocks",
    "Forest and semi natural areas;Open spaces with little or no vegetation;Sparsely vegetated areas",
    "Forest and semi natural areas;Open spaces with little or no vegetation;Burnt areas",
    "Forest and semi natural areas;Open spaces with little or no vegetation;Glaciers and perpetual snow",
    "Wetlands;Inland wetlands;Inland marshes",
    "Wetlands;Inland wetlands;Peat bogs",
    "Wetlands;Maritime wetlands;Salt marshes",
    "Wetlands;Maritime wetlands;Salines",
    "Wetlands;Maritime wetlands;Intertidal flats",
    "Water bodies;Inland waters;Water courses",
    "Water bodies;Inland waters;Water bodies",
    "Water bodies;Marine waters;Coastal lagoons",
    "Water bodies;Marine waters;Estuaries",
    "Water bodies;Marine waters;Sea and ocean"
]